-- Chootistoys seed data: 10 categories, 5 subcategories each, 5 products each subcategory
-- 25 products per category, 250 products total. No image data (image columns left NULL).

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE products;
TRUNCATE TABLE subcategories;
TRUNCATE TABLE categories;
SET FOREIGN_KEY_CHECKS = 1;

-- ==========================
-- Categories
-- ==========================
INSERT INTO categories (name, slug, image, is_active) VALUES
('Soft Toys', 'soft-toys', NULL, 1),
('Action Figures', 'action-figures', NULL, 1),
('Educational Toys', 'educational-toys', NULL, 1),
('Remote Control Toys', 'remote-control-toys', NULL, 1),
('Building Blocks', 'building-blocks', NULL, 1),
('Dolls & Doll Houses', 'dolls-and-doll-houses', NULL, 1),
('Outdoor & Sports Toys', 'outdoor-and-sports-toys', NULL, 1),
('Puzzles & Board Games', 'puzzles-and-board-games', NULL, 1),
('Musical Toys', 'musical-toys', NULL, 1),
('Baby & Infant Toys', 'baby-and-infant-toys', NULL, 1);

-- ==========================
-- Subcategories
-- ==========================
INSERT INTO subcategories (category_id, name, slug, image, is_active) VALUES
(1, 'Teddy Bears', 'soft-toys-teddy-bears', NULL, 1),
(1, 'Animal Plush', 'soft-toys-animal-plush', NULL, 1),
(1, 'Cartoon Character Plush', 'soft-toys-cartoon-character-plush', NULL, 1),
(1, 'Cushion Toys', 'soft-toys-cushion-toys', NULL, 1),
(1, 'Baby Soft Toys', 'soft-toys-baby-soft-toys', NULL, 1),
(2, 'Superhero Figures', 'action-figures-superhero-figures', NULL, 1),
(2, 'Movie Character Figures', 'action-figures-movie-character-figures', NULL, 1),
(2, 'Military Figures', 'action-figures-military-figures', NULL, 1),
(2, 'Robot Figures', 'action-figures-robot-figures', NULL, 1),
(2, 'Wrestling Figures', 'action-figures-wrestling-figures', NULL, 1),
(3, 'Alphabet & Number Toys', 'educational-toys-alphabet-and-number-toys', NULL, 1),
(3, 'Science Kits', 'educational-toys-science-kits', NULL, 1),
(3, 'Coding & STEM Toys', 'educational-toys-coding-and-stem-toys', NULL, 1),
(3, 'Flash Cards & Learning Boards', 'educational-toys-flash-cards-and-learning-boards', NULL, 1),
(3, 'Montessori Toys', 'educational-toys-montessori-toys', NULL, 1),
(4, 'RC Cars', 'remote-control-toys-rc-cars', NULL, 1),
(4, 'RC Helicopters & Drones', 'remote-control-toys-rc-helicopters-and-drones', NULL, 1),
(4, 'RC Boats', 'remote-control-toys-rc-boats', NULL, 1),
(4, 'RC Robots', 'remote-control-toys-rc-robots', NULL, 1),
(4, 'RC Trucks', 'remote-control-toys-rc-trucks', NULL, 1),
(5, 'Classic Building Blocks', 'building-blocks-classic-building-blocks', NULL, 1),
(5, 'City & Town Sets', 'building-blocks-city-and-town-sets', NULL, 1),
(5, 'Vehicle Building Sets', 'building-blocks-vehicle-building-sets', NULL, 1),
(5, 'Castle & Fantasy Sets', 'building-blocks-castle-and-fantasy-sets', NULL, 1),
(5, 'Mini Figure Blocks', 'building-blocks-mini-figure-blocks', NULL, 1),
(6, 'Fashion Dolls', 'dolls-and-doll-houses-fashion-dolls', NULL, 1),
(6, 'Baby Dolls', 'dolls-and-doll-houses-baby-dolls', NULL, 1),
(6, 'Doll Houses', 'dolls-and-doll-houses-doll-houses', NULL, 1),
(6, 'Doll Accessories', 'dolls-and-doll-houses-doll-accessories', NULL, 1),
(6, 'Princess Dolls', 'dolls-and-doll-houses-princess-dolls', NULL, 1),
(7, 'Bicycles & Tricycles', 'outdoor-and-sports-toys-bicycles-and-tricycles', NULL, 1),
(7, 'Balls & Sports Sets', 'outdoor-and-sports-toys-balls-and-sports-sets', NULL, 1),
(7, 'Water Toys', 'outdoor-and-sports-toys-water-toys', NULL, 1),
(7, 'Swings & Slides', 'outdoor-and-sports-toys-swings-and-slides', NULL, 1),
(7, 'Skating & Scooters', 'outdoor-and-sports-toys-skating-and-scooters', NULL, 1),
(8, 'Jigsaw Puzzles', 'puzzles-and-board-games-jigsaw-puzzles', NULL, 1),
(8, 'Wooden Puzzles', 'puzzles-and-board-games-wooden-puzzles', NULL, 1),
(8, 'Family Board Games', 'puzzles-and-board-games-family-board-games', NULL, 1),
(8, 'Card Games', 'puzzles-and-board-games-card-games', NULL, 1),
(8, 'Strategy Games', 'puzzles-and-board-games-strategy-games', NULL, 1),
(9, 'Toy Instruments', 'musical-toys-toy-instruments', NULL, 1),
(9, 'Musical Learning Toys', 'musical-toys-musical-learning-toys', NULL, 1),
(9, 'Karaoke & Sing-Along', 'musical-toys-karaoke-and-sing-along', NULL, 1),
(9, 'Drum Sets', 'musical-toys-drum-sets', NULL, 1),
(9, 'Piano & Keyboard Toys', 'musical-toys-piano-and-keyboard-toys', NULL, 1),
(10, 'Rattles & Teethers', 'baby-and-infant-toys-rattles-and-teethers', NULL, 1),
(10, 'Baby Gyms & Mobiles', 'baby-and-infant-toys-baby-gyms-and-mobiles', NULL, 1),
(10, 'Stacking & Sorting Toys', 'baby-and-infant-toys-stacking-and-sorting-toys', NULL, 1),
(10, 'Bath Toys', 'baby-and-infant-toys-bath-toys', NULL, 1),
(10, 'Push & Pull Toys', 'baby-and-infant-toys-push-and-pull-toys', NULL, 1);

-- ==========================
-- Products
-- ==========================
INSERT INTO products (category_id, subcategory_id, name, slug, product_code, description, purchase_price, sale_price, discount_percent, stock, image, featured, is_active) VALUES
(1, 1, 'Teddy Bears - Small', 'teddy-bears-small-1', 'CHT-0001', 'Teddy Bears - Small from our Teddy Bears range under Soft Toys. Safe, durable and fun for kids.', 125.00, 175.00, 5, 15, NULL, 0, 1),
(1, 1, 'Teddy Bears - Medium', 'teddy-bears-medium-2', 'CHT-0002', 'Teddy Bears - Medium from our Teddy Bears range under Soft Toys. Safe, durable and fun for kids.', 150.00, 210.00, 10, 20, NULL, 0, 1),
(1, 1, 'Teddy Bears - Large', 'teddy-bears-large-3', 'CHT-0003', 'Teddy Bears - Large from our Teddy Bears range under Soft Toys. Safe, durable and fun for kids.', 175.00, 245.00, 15, 25, NULL, 0, 1),
(1, 1, 'Teddy Bears - Extra Large', 'teddy-bears-extra-large-4', 'CHT-0004', 'Teddy Bears - Extra Large from our Teddy Bears range under Soft Toys. Safe, durable and fun for kids.', 200.00, 280.00, 20, 30, NULL, 0, 1),
(1, 1, 'Teddy Bears - Mini', 'teddy-bears-mini-5', 'CHT-0005', 'Teddy Bears - Mini from our Teddy Bears range under Soft Toys. Safe, durable and fun for kids.', 225.00, 315.00, 0, 35, NULL, 0, 1),
(1, 2, 'Animal Plush - Small', 'animal-plush-small-6', 'CHT-0006', 'Animal Plush - Small from our Animal Plush range under Soft Toys. Safe, durable and fun for kids.', 250.00, 350.00, 5, 40, NULL, 0, 1),
(1, 2, 'Animal Plush - Medium', 'animal-plush-medium-7', 'CHT-0007', 'Animal Plush - Medium from our Animal Plush range under Soft Toys. Safe, durable and fun for kids.', 275.00, 385.00, 10, 45, NULL, 0, 1),
(1, 2, 'Animal Plush - Large', 'animal-plush-large-8', 'CHT-0008', 'Animal Plush - Large from our Animal Plush range under Soft Toys. Safe, durable and fun for kids.', 300.00, 420.00, 15, 50, NULL, 0, 1),
(1, 2, 'Animal Plush - Extra Large', 'animal-plush-extra-large-9', 'CHT-0009', 'Animal Plush - Extra Large from our Animal Plush range under Soft Toys. Safe, durable and fun for kids.', 325.00, 455.00, 20, 55, NULL, 0, 1),
(1, 2, 'Animal Plush - Mini', 'animal-plush-mini-10', 'CHT-0010', 'Animal Plush - Mini from our Animal Plush range under Soft Toys. Safe, durable and fun for kids.', 350.00, 490.00, 0, 60, NULL, 0, 1),
(1, 3, 'Cartoon Character Plush - Small', 'cartoon-character-plush-small-11', 'CHT-0011', 'Cartoon Character Plush - Small from our Cartoon Character Plush range under Soft Toys. Safe, durable and fun for kids.', 375.00, 525.00, 5, 65, NULL, 0, 1),
(1, 3, 'Cartoon Character Plush - Medium', 'cartoon-character-plush-medium-12', 'CHT-0012', 'Cartoon Character Plush - Medium from our Cartoon Character Plush range under Soft Toys. Safe, durable and fun for kids.', 400.00, 560.00, 10, 70, NULL, 0, 1),
(1, 3, 'Cartoon Character Plush - Large', 'cartoon-character-plush-large-13', 'CHT-0013', 'Cartoon Character Plush - Large from our Cartoon Character Plush range under Soft Toys. Safe, durable and fun for kids.', 425.00, 595.00, 15, 75, NULL, 0, 1),
(1, 3, 'Cartoon Character Plush - Extra Large', 'cartoon-character-plush-extra-large-14', 'CHT-0014', 'Cartoon Character Plush - Extra Large from our Cartoon Character Plush range under Soft Toys. Safe, durable and fun for kids.', 450.00, 630.00, 20, 80, NULL, 0, 1),
(1, 3, 'Cartoon Character Plush - Mini', 'cartoon-character-plush-mini-15', 'CHT-0015', 'Cartoon Character Plush - Mini from our Cartoon Character Plush range under Soft Toys. Safe, durable and fun for kids.', 475.00, 665.00, 0, 10, NULL, 0, 1),
(1, 4, 'Cushion Toys - Small', 'cushion-toys-small-16', 'CHT-0016', 'Cushion Toys - Small from our Cushion Toys range under Soft Toys. Safe, durable and fun for kids.', 500.00, 700.00, 5, 15, NULL, 0, 1),
(1, 4, 'Cushion Toys - Medium', 'cushion-toys-medium-17', 'CHT-0017', 'Cushion Toys - Medium from our Cushion Toys range under Soft Toys. Safe, durable and fun for kids.', 525.00, 735.00, 10, 20, NULL, 1, 1),
(1, 4, 'Cushion Toys - Large', 'cushion-toys-large-18', 'CHT-0018', 'Cushion Toys - Large from our Cushion Toys range under Soft Toys. Safe, durable and fun for kids.', 550.00, 770.00, 15, 25, NULL, 0, 1),
(1, 4, 'Cushion Toys - Extra Large', 'cushion-toys-extra-large-19', 'CHT-0019', 'Cushion Toys - Extra Large from our Cushion Toys range under Soft Toys. Safe, durable and fun for kids.', 575.00, 805.00, 20, 30, NULL, 0, 1),
(1, 4, 'Cushion Toys - Mini', 'cushion-toys-mini-20', 'CHT-0020', 'Cushion Toys - Mini from our Cushion Toys range under Soft Toys. Safe, durable and fun for kids.', 100.00, 140.00, 0, 35, NULL, 0, 1),
(1, 5, 'Baby Soft Toys - Small', 'baby-soft-toys-small-21', 'CHT-0021', 'Baby Soft Toys - Small from our Baby Soft Toys range under Soft Toys. Safe, durable and fun for kids.', 125.00, 175.00, 5, 40, NULL, 0, 1),
(1, 5, 'Baby Soft Toys - Medium', 'baby-soft-toys-medium-22', 'CHT-0022', 'Baby Soft Toys - Medium from our Baby Soft Toys range under Soft Toys. Safe, durable and fun for kids.', 150.00, 210.00, 10, 45, NULL, 0, 1),
(1, 5, 'Baby Soft Toys - Large', 'baby-soft-toys-large-23', 'CHT-0023', 'Baby Soft Toys - Large from our Baby Soft Toys range under Soft Toys. Safe, durable and fun for kids.', 175.00, 245.00, 15, 50, NULL, 0, 1),
(1, 5, 'Baby Soft Toys - Extra Large', 'baby-soft-toys-extra-large-24', 'CHT-0024', 'Baby Soft Toys - Extra Large from our Baby Soft Toys range under Soft Toys. Safe, durable and fun for kids.', 200.00, 280.00, 20, 55, NULL, 0, 1),
(1, 5, 'Baby Soft Toys - Mini', 'baby-soft-toys-mini-25', 'CHT-0025', 'Baby Soft Toys - Mini from our Baby Soft Toys range under Soft Toys. Safe, durable and fun for kids.', 225.00, 315.00, 0, 60, NULL, 0, 1),
(2, 6, 'Superhero Figures - Standard Edition', 'superhero-figures-standard-edition-26', 'CHT-0026', 'Superhero Figures - Standard Edition from our Superhero Figures range under Action Figures. Safe, durable and fun for kids.', 250.00, 350.00, 5, 65, NULL, 0, 1),
(2, 6, 'Superhero Figures - Deluxe Edition', 'superhero-figures-deluxe-edition-27', 'CHT-0027', 'Superhero Figures - Deluxe Edition from our Superhero Figures range under Action Figures. Safe, durable and fun for kids.', 275.00, 385.00, 10, 70, NULL, 0, 1),
(2, 6, 'Superhero Figures - Battle Pack', 'superhero-figures-battle-pack-28', 'CHT-0028', 'Superhero Figures - Battle Pack from our Superhero Figures range under Action Figures. Safe, durable and fun for kids.', 300.00, 420.00, 15, 75, NULL, 0, 1),
(2, 6, 'Superhero Figures - Collector''s Edition', 'superhero-figures-collector-s-edition-29', 'CHT-0029', 'Superhero Figures - Collector''s Edition from our Superhero Figures range under Action Figures. Safe, durable and fun for kids.', 325.00, 455.00, 20, 80, NULL, 0, 1),
(2, 6, 'Superhero Figures - Mini Pack', 'superhero-figures-mini-pack-30', 'CHT-0030', 'Superhero Figures - Mini Pack from our Superhero Figures range under Action Figures. Safe, durable and fun for kids.', 350.00, 490.00, 0, 10, NULL, 0, 1),
(2, 7, 'Movie Character Figures - Standard Edition', 'movie-character-figures-standard-edition-31', 'CHT-0031', 'Movie Character Figures - Standard Edition from our Movie Character Figures range under Action Figures. Safe, durable and fun for kids.', 375.00, 525.00, 5, 15, NULL, 0, 1),
(2, 7, 'Movie Character Figures - Deluxe Edition', 'movie-character-figures-deluxe-edition-32', 'CHT-0032', 'Movie Character Figures - Deluxe Edition from our Movie Character Figures range under Action Figures. Safe, durable and fun for kids.', 400.00, 560.00, 10, 20, NULL, 0, 1),
(2, 7, 'Movie Character Figures - Battle Pack', 'movie-character-figures-battle-pack-33', 'CHT-0033', 'Movie Character Figures - Battle Pack from our Movie Character Figures range under Action Figures. Safe, durable and fun for kids.', 425.00, 595.00, 15, 25, NULL, 0, 1),
(2, 7, 'Movie Character Figures - Collector''s Edition', 'movie-character-figures-collector-s-edition-34', 'CHT-0034', 'Movie Character Figures - Collector''s Edition from our Movie Character Figures range under Action Figures. Safe, durable and fun for kids.', 450.00, 630.00, 20, 30, NULL, 1, 1),
(2, 7, 'Movie Character Figures - Mini Pack', 'movie-character-figures-mini-pack-35', 'CHT-0035', 'Movie Character Figures - Mini Pack from our Movie Character Figures range under Action Figures. Safe, durable and fun for kids.', 475.00, 665.00, 0, 35, NULL, 0, 1),
(2, 8, 'Military Figures - Standard Edition', 'military-figures-standard-edition-36', 'CHT-0036', 'Military Figures - Standard Edition from our Military Figures range under Action Figures. Safe, durable and fun for kids.', 500.00, 700.00, 5, 40, NULL, 0, 1),
(2, 8, 'Military Figures - Deluxe Edition', 'military-figures-deluxe-edition-37', 'CHT-0037', 'Military Figures - Deluxe Edition from our Military Figures range under Action Figures. Safe, durable and fun for kids.', 525.00, 735.00, 10, 45, NULL, 0, 1),
(2, 8, 'Military Figures - Battle Pack', 'military-figures-battle-pack-38', 'CHT-0038', 'Military Figures - Battle Pack from our Military Figures range under Action Figures. Safe, durable and fun for kids.', 550.00, 770.00, 15, 50, NULL, 0, 1),
(2, 8, 'Military Figures - Collector''s Edition', 'military-figures-collector-s-edition-39', 'CHT-0039', 'Military Figures - Collector''s Edition from our Military Figures range under Action Figures. Safe, durable and fun for kids.', 575.00, 805.00, 20, 55, NULL, 0, 1),
(2, 8, 'Military Figures - Mini Pack', 'military-figures-mini-pack-40', 'CHT-0040', 'Military Figures - Mini Pack from our Military Figures range under Action Figures. Safe, durable and fun for kids.', 100.00, 140.00, 0, 60, NULL, 0, 1),
(2, 9, 'Robot Figures - Standard Edition', 'robot-figures-standard-edition-41', 'CHT-0041', 'Robot Figures - Standard Edition from our Robot Figures range under Action Figures. Safe, durable and fun for kids.', 125.00, 175.00, 5, 65, NULL, 0, 1),
(2, 9, 'Robot Figures - Deluxe Edition', 'robot-figures-deluxe-edition-42', 'CHT-0042', 'Robot Figures - Deluxe Edition from our Robot Figures range under Action Figures. Safe, durable and fun for kids.', 150.00, 210.00, 10, 70, NULL, 0, 1),
(2, 9, 'Robot Figures - Battle Pack', 'robot-figures-battle-pack-43', 'CHT-0043', 'Robot Figures - Battle Pack from our Robot Figures range under Action Figures. Safe, durable and fun for kids.', 175.00, 245.00, 15, 75, NULL, 0, 1),
(2, 9, 'Robot Figures - Collector''s Edition', 'robot-figures-collector-s-edition-44', 'CHT-0044', 'Robot Figures - Collector''s Edition from our Robot Figures range under Action Figures. Safe, durable and fun for kids.', 200.00, 280.00, 20, 80, NULL, 0, 1),
(2, 9, 'Robot Figures - Mini Pack', 'robot-figures-mini-pack-45', 'CHT-0045', 'Robot Figures - Mini Pack from our Robot Figures range under Action Figures. Safe, durable and fun for kids.', 225.00, 315.00, 0, 10, NULL, 0, 1),
(2, 10, 'Wrestling Figures - Standard Edition', 'wrestling-figures-standard-edition-46', 'CHT-0046', 'Wrestling Figures - Standard Edition from our Wrestling Figures range under Action Figures. Safe, durable and fun for kids.', 250.00, 350.00, 5, 15, NULL, 0, 1),
(2, 10, 'Wrestling Figures - Deluxe Edition', 'wrestling-figures-deluxe-edition-47', 'CHT-0047', 'Wrestling Figures - Deluxe Edition from our Wrestling Figures range under Action Figures. Safe, durable and fun for kids.', 275.00, 385.00, 10, 20, NULL, 0, 1),
(2, 10, 'Wrestling Figures - Battle Pack', 'wrestling-figures-battle-pack-48', 'CHT-0048', 'Wrestling Figures - Battle Pack from our Wrestling Figures range under Action Figures. Safe, durable and fun for kids.', 300.00, 420.00, 15, 25, NULL, 0, 1),
(2, 10, 'Wrestling Figures - Collector''s Edition', 'wrestling-figures-collector-s-edition-49', 'CHT-0049', 'Wrestling Figures - Collector''s Edition from our Wrestling Figures range under Action Figures. Safe, durable and fun for kids.', 325.00, 455.00, 20, 30, NULL, 0, 1),
(2, 10, 'Wrestling Figures - Mini Pack', 'wrestling-figures-mini-pack-50', 'CHT-0050', 'Wrestling Figures - Mini Pack from our Wrestling Figures range under Action Figures. Safe, durable and fun for kids.', 350.00, 490.00, 0, 35, NULL, 0, 1),
(3, 11, 'Alphabet & Number Toys - Beginner Set', 'alphabet-and-number-toys-beginner-set-51', 'CHT-0051', 'Alphabet & Number Toys - Beginner Set from our Alphabet & Number Toys range under Educational Toys. Safe, durable and fun for kids.', 375.00, 525.00, 5, 40, NULL, 1, 1),
(3, 11, 'Alphabet & Number Toys - Advanced Set', 'alphabet-and-number-toys-advanced-set-52', 'CHT-0052', 'Alphabet & Number Toys - Advanced Set from our Alphabet & Number Toys range under Educational Toys. Safe, durable and fun for kids.', 400.00, 560.00, 10, 45, NULL, 0, 1),
(3, 11, 'Alphabet & Number Toys - Junior Kit', 'alphabet-and-number-toys-junior-kit-53', 'CHT-0053', 'Alphabet & Number Toys - Junior Kit from our Alphabet & Number Toys range under Educational Toys. Safe, durable and fun for kids.', 425.00, 595.00, 15, 50, NULL, 0, 1),
(3, 11, 'Alphabet & Number Toys - Classic Kit', 'alphabet-and-number-toys-classic-kit-54', 'CHT-0054', 'Alphabet & Number Toys - Classic Kit from our Alphabet & Number Toys range under Educational Toys. Safe, durable and fun for kids.', 450.00, 630.00, 20, 55, NULL, 0, 1),
(3, 11, 'Alphabet & Number Toys - Starter Pack', 'alphabet-and-number-toys-starter-pack-55', 'CHT-0055', 'Alphabet & Number Toys - Starter Pack from our Alphabet & Number Toys range under Educational Toys. Safe, durable and fun for kids.', 475.00, 665.00, 0, 60, NULL, 0, 1),
(3, 12, 'Science Kits - Beginner Set', 'science-kits-beginner-set-56', 'CHT-0056', 'Science Kits - Beginner Set from our Science Kits range under Educational Toys. Safe, durable and fun for kids.', 500.00, 700.00, 5, 65, NULL, 0, 1),
(3, 12, 'Science Kits - Advanced Set', 'science-kits-advanced-set-57', 'CHT-0057', 'Science Kits - Advanced Set from our Science Kits range under Educational Toys. Safe, durable and fun for kids.', 525.00, 735.00, 10, 70, NULL, 0, 1),
(3, 12, 'Science Kits - Junior Kit', 'science-kits-junior-kit-58', 'CHT-0058', 'Science Kits - Junior Kit from our Science Kits range under Educational Toys. Safe, durable and fun for kids.', 550.00, 770.00, 15, 75, NULL, 0, 1),
(3, 12, 'Science Kits - Classic Kit', 'science-kits-classic-kit-59', 'CHT-0059', 'Science Kits - Classic Kit from our Science Kits range under Educational Toys. Safe, durable and fun for kids.', 575.00, 805.00, 20, 80, NULL, 0, 1),
(3, 12, 'Science Kits - Starter Pack', 'science-kits-starter-pack-60', 'CHT-0060', 'Science Kits - Starter Pack from our Science Kits range under Educational Toys. Safe, durable and fun for kids.', 100.00, 140.00, 0, 10, NULL, 0, 1),
(3, 13, 'Coding & STEM Toys - Beginner Set', 'coding-and-stem-toys-beginner-set-61', 'CHT-0061', 'Coding & STEM Toys - Beginner Set from our Coding & STEM Toys range under Educational Toys. Safe, durable and fun for kids.', 125.00, 175.00, 5, 15, NULL, 0, 1),
(3, 13, 'Coding & STEM Toys - Advanced Set', 'coding-and-stem-toys-advanced-set-62', 'CHT-0062', 'Coding & STEM Toys - Advanced Set from our Coding & STEM Toys range under Educational Toys. Safe, durable and fun for kids.', 150.00, 210.00, 10, 20, NULL, 0, 1),
(3, 13, 'Coding & STEM Toys - Junior Kit', 'coding-and-stem-toys-junior-kit-63', 'CHT-0063', 'Coding & STEM Toys - Junior Kit from our Coding & STEM Toys range under Educational Toys. Safe, durable and fun for kids.', 175.00, 245.00, 15, 25, NULL, 0, 1),
(3, 13, 'Coding & STEM Toys - Classic Kit', 'coding-and-stem-toys-classic-kit-64', 'CHT-0064', 'Coding & STEM Toys - Classic Kit from our Coding & STEM Toys range under Educational Toys. Safe, durable and fun for kids.', 200.00, 280.00, 20, 30, NULL, 0, 1),
(3, 13, 'Coding & STEM Toys - Starter Pack', 'coding-and-stem-toys-starter-pack-65', 'CHT-0065', 'Coding & STEM Toys - Starter Pack from our Coding & STEM Toys range under Educational Toys. Safe, durable and fun for kids.', 225.00, 315.00, 0, 35, NULL, 0, 1),
(3, 14, 'Flash Cards & Learning Boards - Beginner Set', 'flash-cards-and-learning-boards-beginner-set-66', 'CHT-0066', 'Flash Cards & Learning Boards - Beginner Set from our Flash Cards & Learning Boards range under Educational Toys. Safe, durable and fun for kids.', 250.00, 350.00, 5, 40, NULL, 0, 1),
(3, 14, 'Flash Cards & Learning Boards - Advanced Set', 'flash-cards-and-learning-boards-advanced-set-67', 'CHT-0067', 'Flash Cards & Learning Boards - Advanced Set from our Flash Cards & Learning Boards range under Educational Toys. Safe, durable and fun for kids.', 275.00, 385.00, 10, 45, NULL, 0, 1),
(3, 14, 'Flash Cards & Learning Boards - Junior Kit', 'flash-cards-and-learning-boards-junior-kit-68', 'CHT-0068', 'Flash Cards & Learning Boards - Junior Kit from our Flash Cards & Learning Boards range under Educational Toys. Safe, durable and fun for kids.', 300.00, 420.00, 15, 50, NULL, 1, 1),
(3, 14, 'Flash Cards & Learning Boards - Classic Kit', 'flash-cards-and-learning-boards-classic-kit-69', 'CHT-0069', 'Flash Cards & Learning Boards - Classic Kit from our Flash Cards & Learning Boards range under Educational Toys. Safe, durable and fun for kids.', 325.00, 455.00, 20, 55, NULL, 0, 1),
(3, 14, 'Flash Cards & Learning Boards - Starter Pack', 'flash-cards-and-learning-boards-starter-pack-70', 'CHT-0070', 'Flash Cards & Learning Boards - Starter Pack from our Flash Cards & Learning Boards range under Educational Toys. Safe, durable and fun for kids.', 350.00, 490.00, 0, 60, NULL, 0, 1),
(3, 15, 'Montessori Toys - Beginner Set', 'montessori-toys-beginner-set-71', 'CHT-0071', 'Montessori Toys - Beginner Set from our Montessori Toys range under Educational Toys. Safe, durable and fun for kids.', 375.00, 525.00, 5, 65, NULL, 0, 1),
(3, 15, 'Montessori Toys - Advanced Set', 'montessori-toys-advanced-set-72', 'CHT-0072', 'Montessori Toys - Advanced Set from our Montessori Toys range under Educational Toys. Safe, durable and fun for kids.', 400.00, 560.00, 10, 70, NULL, 0, 1),
(3, 15, 'Montessori Toys - Junior Kit', 'montessori-toys-junior-kit-73', 'CHT-0073', 'Montessori Toys - Junior Kit from our Montessori Toys range under Educational Toys. Safe, durable and fun for kids.', 425.00, 595.00, 15, 75, NULL, 0, 1),
(3, 15, 'Montessori Toys - Classic Kit', 'montessori-toys-classic-kit-74', 'CHT-0074', 'Montessori Toys - Classic Kit from our Montessori Toys range under Educational Toys. Safe, durable and fun for kids.', 450.00, 630.00, 20, 80, NULL, 0, 1),
(3, 15, 'Montessori Toys - Starter Pack', 'montessori-toys-starter-pack-75', 'CHT-0075', 'Montessori Toys - Starter Pack from our Montessori Toys range under Educational Toys. Safe, durable and fun for kids.', 475.00, 665.00, 0, 10, NULL, 0, 1),
(4, 16, 'RC Cars - Red Edition', 'rc-cars-red-edition-76', 'CHT-0076', 'RC Cars - Red Edition from our RC Cars range under Remote Control Toys. Safe, durable and fun for kids.', 500.00, 700.00, 5, 15, NULL, 0, 1),
(4, 16, 'RC Cars - Blue Edition', 'rc-cars-blue-edition-77', 'CHT-0077', 'RC Cars - Blue Edition from our RC Cars range under Remote Control Toys. Safe, durable and fun for kids.', 525.00, 735.00, 10, 20, NULL, 0, 1),
(4, 16, 'RC Cars - Off-Road Pack', 'rc-cars-off-road-pack-78', 'CHT-0078', 'RC Cars - Off-Road Pack from our RC Cars range under Remote Control Toys. Safe, durable and fun for kids.', 550.00, 770.00, 15, 25, NULL, 0, 1),
(4, 16, 'RC Cars - Speed Edition', 'rc-cars-speed-edition-79', 'CHT-0079', 'RC Cars - Speed Edition from our RC Cars range under Remote Control Toys. Safe, durable and fun for kids.', 575.00, 805.00, 20, 30, NULL, 0, 1),
(4, 16, 'RC Cars - Pro Series', 'rc-cars-pro-series-80', 'CHT-0080', 'RC Cars - Pro Series from our RC Cars range under Remote Control Toys. Safe, durable and fun for kids.', 100.00, 140.00, 0, 35, NULL, 0, 1),
(4, 17, 'RC Helicopters & Drones - Red Edition', 'rc-helicopters-and-drones-red-edition-81', 'CHT-0081', 'RC Helicopters & Drones - Red Edition from our RC Helicopters & Drones range under Remote Control Toys. Safe, durable and fun for kids.', 125.00, 175.00, 5, 40, NULL, 0, 1),
(4, 17, 'RC Helicopters & Drones - Blue Edition', 'rc-helicopters-and-drones-blue-edition-82', 'CHT-0082', 'RC Helicopters & Drones - Blue Edition from our RC Helicopters & Drones range under Remote Control Toys. Safe, durable and fun for kids.', 150.00, 210.00, 10, 45, NULL, 0, 1),
(4, 17, 'RC Helicopters & Drones - Off-Road Pack', 'rc-helicopters-and-drones-off-road-pack-83', 'CHT-0083', 'RC Helicopters & Drones - Off-Road Pack from our RC Helicopters & Drones range under Remote Control Toys. Safe, durable and fun for kids.', 175.00, 245.00, 15, 50, NULL, 0, 1),
(4, 17, 'RC Helicopters & Drones - Speed Edition', 'rc-helicopters-and-drones-speed-edition-84', 'CHT-0084', 'RC Helicopters & Drones - Speed Edition from our RC Helicopters & Drones range under Remote Control Toys. Safe, durable and fun for kids.', 200.00, 280.00, 20, 55, NULL, 0, 1),
(4, 17, 'RC Helicopters & Drones - Pro Series', 'rc-helicopters-and-drones-pro-series-85', 'CHT-0085', 'RC Helicopters & Drones - Pro Series from our RC Helicopters & Drones range under Remote Control Toys. Safe, durable and fun for kids.', 225.00, 315.00, 0, 60, NULL, 1, 1),
(4, 18, 'RC Boats - Red Edition', 'rc-boats-red-edition-86', 'CHT-0086', 'RC Boats - Red Edition from our RC Boats range under Remote Control Toys. Safe, durable and fun for kids.', 250.00, 350.00, 5, 65, NULL, 0, 1),
(4, 18, 'RC Boats - Blue Edition', 'rc-boats-blue-edition-87', 'CHT-0087', 'RC Boats - Blue Edition from our RC Boats range under Remote Control Toys. Safe, durable and fun for kids.', 275.00, 385.00, 10, 70, NULL, 0, 1),
(4, 18, 'RC Boats - Off-Road Pack', 'rc-boats-off-road-pack-88', 'CHT-0088', 'RC Boats - Off-Road Pack from our RC Boats range under Remote Control Toys. Safe, durable and fun for kids.', 300.00, 420.00, 15, 75, NULL, 0, 1),
(4, 18, 'RC Boats - Speed Edition', 'rc-boats-speed-edition-89', 'CHT-0089', 'RC Boats - Speed Edition from our RC Boats range under Remote Control Toys. Safe, durable and fun for kids.', 325.00, 455.00, 20, 80, NULL, 0, 1),
(4, 18, 'RC Boats - Pro Series', 'rc-boats-pro-series-90', 'CHT-0090', 'RC Boats - Pro Series from our RC Boats range under Remote Control Toys. Safe, durable and fun for kids.', 350.00, 490.00, 0, 10, NULL, 0, 1),
(4, 19, 'RC Robots - Red Edition', 'rc-robots-red-edition-91', 'CHT-0091', 'RC Robots - Red Edition from our RC Robots range under Remote Control Toys. Safe, durable and fun for kids.', 375.00, 525.00, 5, 15, NULL, 0, 1),
(4, 19, 'RC Robots - Blue Edition', 'rc-robots-blue-edition-92', 'CHT-0092', 'RC Robots - Blue Edition from our RC Robots range under Remote Control Toys. Safe, durable and fun for kids.', 400.00, 560.00, 10, 20, NULL, 0, 1),
(4, 19, 'RC Robots - Off-Road Pack', 'rc-robots-off-road-pack-93', 'CHT-0093', 'RC Robots - Off-Road Pack from our RC Robots range under Remote Control Toys. Safe, durable and fun for kids.', 425.00, 595.00, 15, 25, NULL, 0, 1),
(4, 19, 'RC Robots - Speed Edition', 'rc-robots-speed-edition-94', 'CHT-0094', 'RC Robots - Speed Edition from our RC Robots range under Remote Control Toys. Safe, durable and fun for kids.', 450.00, 630.00, 20, 30, NULL, 0, 1),
(4, 19, 'RC Robots - Pro Series', 'rc-robots-pro-series-95', 'CHT-0095', 'RC Robots - Pro Series from our RC Robots range under Remote Control Toys. Safe, durable and fun for kids.', 475.00, 665.00, 0, 35, NULL, 0, 1),
(4, 20, 'RC Trucks - Red Edition', 'rc-trucks-red-edition-96', 'CHT-0096', 'RC Trucks - Red Edition from our RC Trucks range under Remote Control Toys. Safe, durable and fun for kids.', 500.00, 700.00, 5, 40, NULL, 0, 1),
(4, 20, 'RC Trucks - Blue Edition', 'rc-trucks-blue-edition-97', 'CHT-0097', 'RC Trucks - Blue Edition from our RC Trucks range under Remote Control Toys. Safe, durable and fun for kids.', 525.00, 735.00, 10, 45, NULL, 0, 1),
(4, 20, 'RC Trucks - Off-Road Pack', 'rc-trucks-off-road-pack-98', 'CHT-0098', 'RC Trucks - Off-Road Pack from our RC Trucks range under Remote Control Toys. Safe, durable and fun for kids.', 550.00, 770.00, 15, 50, NULL, 0, 1),
(4, 20, 'RC Trucks - Speed Edition', 'rc-trucks-speed-edition-99', 'CHT-0099', 'RC Trucks - Speed Edition from our RC Trucks range under Remote Control Toys. Safe, durable and fun for kids.', 575.00, 805.00, 20, 55, NULL, 0, 1),
(4, 20, 'RC Trucks - Pro Series', 'rc-trucks-pro-series-100', 'CHT-0100', 'RC Trucks - Pro Series from our RC Trucks range under Remote Control Toys. Safe, durable and fun for kids.', 100.00, 140.00, 0, 60, NULL, 0, 1),
(5, 21, 'Classic Building Blocks - 100 Piece Set', 'classic-building-blocks-100-piece-set-101', 'CHT-0101', 'Classic Building Blocks - 100 Piece Set from our Classic Building Blocks range under Building Blocks. Safe, durable and fun for kids.', 125.00, 175.00, 5, 65, NULL, 0, 1),
(5, 21, 'Classic Building Blocks - 250 Piece Set', 'classic-building-blocks-250-piece-set-102', 'CHT-0102', 'Classic Building Blocks - 250 Piece Set from our Classic Building Blocks range under Building Blocks. Safe, durable and fun for kids.', 150.00, 210.00, 10, 70, NULL, 1, 1),
(5, 21, 'Classic Building Blocks - 500 Piece Set', 'classic-building-blocks-500-piece-set-103', 'CHT-0103', 'Classic Building Blocks - 500 Piece Set from our Classic Building Blocks range under Building Blocks. Safe, durable and fun for kids.', 175.00, 245.00, 15, 75, NULL, 0, 1),
(5, 21, 'Classic Building Blocks - Starter Box', 'classic-building-blocks-starter-box-104', 'CHT-0104', 'Classic Building Blocks - Starter Box from our Classic Building Blocks range under Building Blocks. Safe, durable and fun for kids.', 200.00, 280.00, 20, 80, NULL, 0, 1),
(5, 21, 'Classic Building Blocks - Mega Pack', 'classic-building-blocks-mega-pack-105', 'CHT-0105', 'Classic Building Blocks - Mega Pack from our Classic Building Blocks range under Building Blocks. Safe, durable and fun for kids.', 225.00, 315.00, 0, 10, NULL, 0, 1),
(5, 22, 'City & Town Sets - 100 Piece Set', 'city-and-town-sets-100-piece-set-106', 'CHT-0106', 'City & Town Sets - 100 Piece Set from our City & Town Sets range under Building Blocks. Safe, durable and fun for kids.', 250.00, 350.00, 5, 15, NULL, 0, 1),
(5, 22, 'City & Town Sets - 250 Piece Set', 'city-and-town-sets-250-piece-set-107', 'CHT-0107', 'City & Town Sets - 250 Piece Set from our City & Town Sets range under Building Blocks. Safe, durable and fun for kids.', 275.00, 385.00, 10, 20, NULL, 0, 1),
(5, 22, 'City & Town Sets - 500 Piece Set', 'city-and-town-sets-500-piece-set-108', 'CHT-0108', 'City & Town Sets - 500 Piece Set from our City & Town Sets range under Building Blocks. Safe, durable and fun for kids.', 300.00, 420.00, 15, 25, NULL, 0, 1),
(5, 22, 'City & Town Sets - Starter Box', 'city-and-town-sets-starter-box-109', 'CHT-0109', 'City & Town Sets - Starter Box from our City & Town Sets range under Building Blocks. Safe, durable and fun for kids.', 325.00, 455.00, 20, 30, NULL, 0, 1),
(5, 22, 'City & Town Sets - Mega Pack', 'city-and-town-sets-mega-pack-110', 'CHT-0110', 'City & Town Sets - Mega Pack from our City & Town Sets range under Building Blocks. Safe, durable and fun for kids.', 350.00, 490.00, 0, 35, NULL, 0, 1),
(5, 23, 'Vehicle Building Sets - 100 Piece Set', 'vehicle-building-sets-100-piece-set-111', 'CHT-0111', 'Vehicle Building Sets - 100 Piece Set from our Vehicle Building Sets range under Building Blocks. Safe, durable and fun for kids.', 375.00, 525.00, 5, 40, NULL, 0, 1),
(5, 23, 'Vehicle Building Sets - 250 Piece Set', 'vehicle-building-sets-250-piece-set-112', 'CHT-0112', 'Vehicle Building Sets - 250 Piece Set from our Vehicle Building Sets range under Building Blocks. Safe, durable and fun for kids.', 400.00, 560.00, 10, 45, NULL, 0, 1),
(5, 23, 'Vehicle Building Sets - 500 Piece Set', 'vehicle-building-sets-500-piece-set-113', 'CHT-0113', 'Vehicle Building Sets - 500 Piece Set from our Vehicle Building Sets range under Building Blocks. Safe, durable and fun for kids.', 425.00, 595.00, 15, 50, NULL, 0, 1),
(5, 23, 'Vehicle Building Sets - Starter Box', 'vehicle-building-sets-starter-box-114', 'CHT-0114', 'Vehicle Building Sets - Starter Box from our Vehicle Building Sets range under Building Blocks. Safe, durable and fun for kids.', 450.00, 630.00, 20, 55, NULL, 0, 1),
(5, 23, 'Vehicle Building Sets - Mega Pack', 'vehicle-building-sets-mega-pack-115', 'CHT-0115', 'Vehicle Building Sets - Mega Pack from our Vehicle Building Sets range under Building Blocks. Safe, durable and fun for kids.', 475.00, 665.00, 0, 60, NULL, 0, 1),
(5, 24, 'Castle & Fantasy Sets - 100 Piece Set', 'castle-and-fantasy-sets-100-piece-set-116', 'CHT-0116', 'Castle & Fantasy Sets - 100 Piece Set from our Castle & Fantasy Sets range under Building Blocks. Safe, durable and fun for kids.', 500.00, 700.00, 5, 65, NULL, 0, 1),
(5, 24, 'Castle & Fantasy Sets - 250 Piece Set', 'castle-and-fantasy-sets-250-piece-set-117', 'CHT-0117', 'Castle & Fantasy Sets - 250 Piece Set from our Castle & Fantasy Sets range under Building Blocks. Safe, durable and fun for kids.', 525.00, 735.00, 10, 70, NULL, 0, 1),
(5, 24, 'Castle & Fantasy Sets - 500 Piece Set', 'castle-and-fantasy-sets-500-piece-set-118', 'CHT-0118', 'Castle & Fantasy Sets - 500 Piece Set from our Castle & Fantasy Sets range under Building Blocks. Safe, durable and fun for kids.', 550.00, 770.00, 15, 75, NULL, 0, 1),
(5, 24, 'Castle & Fantasy Sets - Starter Box', 'castle-and-fantasy-sets-starter-box-119', 'CHT-0119', 'Castle & Fantasy Sets - Starter Box from our Castle & Fantasy Sets range under Building Blocks. Safe, durable and fun for kids.', 575.00, 805.00, 20, 80, NULL, 1, 1),
(5, 24, 'Castle & Fantasy Sets - Mega Pack', 'castle-and-fantasy-sets-mega-pack-120', 'CHT-0120', 'Castle & Fantasy Sets - Mega Pack from our Castle & Fantasy Sets range under Building Blocks. Safe, durable and fun for kids.', 100.00, 140.00, 0, 10, NULL, 0, 1),
(5, 25, 'Mini Figure Blocks - 100 Piece Set', 'mini-figure-blocks-100-piece-set-121', 'CHT-0121', 'Mini Figure Blocks - 100 Piece Set from our Mini Figure Blocks range under Building Blocks. Safe, durable and fun for kids.', 125.00, 175.00, 5, 15, NULL, 0, 1),
(5, 25, 'Mini Figure Blocks - 250 Piece Set', 'mini-figure-blocks-250-piece-set-122', 'CHT-0122', 'Mini Figure Blocks - 250 Piece Set from our Mini Figure Blocks range under Building Blocks. Safe, durable and fun for kids.', 150.00, 210.00, 10, 20, NULL, 0, 1),
(5, 25, 'Mini Figure Blocks - 500 Piece Set', 'mini-figure-blocks-500-piece-set-123', 'CHT-0123', 'Mini Figure Blocks - 500 Piece Set from our Mini Figure Blocks range under Building Blocks. Safe, durable and fun for kids.', 175.00, 245.00, 15, 25, NULL, 0, 1),
(5, 25, 'Mini Figure Blocks - Starter Box', 'mini-figure-blocks-starter-box-124', 'CHT-0124', 'Mini Figure Blocks - Starter Box from our Mini Figure Blocks range under Building Blocks. Safe, durable and fun for kids.', 200.00, 280.00, 20, 30, NULL, 0, 1),
(5, 25, 'Mini Figure Blocks - Mega Pack', 'mini-figure-blocks-mega-pack-125', 'CHT-0125', 'Mini Figure Blocks - Mega Pack from our Mini Figure Blocks range under Building Blocks. Safe, durable and fun for kids.', 225.00, 315.00, 0, 35, NULL, 0, 1),
(6, 26, 'Fashion Dolls - Classic Look', 'fashion-dolls-classic-look-126', 'CHT-0126', 'Fashion Dolls - Classic Look from our Fashion Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 250.00, 350.00, 5, 40, NULL, 0, 1),
(6, 26, 'Fashion Dolls - Party Wear', 'fashion-dolls-party-wear-127', 'CHT-0127', 'Fashion Dolls - Party Wear from our Fashion Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 275.00, 385.00, 10, 45, NULL, 0, 1),
(6, 26, 'Fashion Dolls - Everyday Wear', 'fashion-dolls-everyday-wear-128', 'CHT-0128', 'Fashion Dolls - Everyday Wear from our Fashion Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 300.00, 420.00, 15, 50, NULL, 0, 1),
(6, 26, 'Fashion Dolls - Deluxe Set', 'fashion-dolls-deluxe-set-129', 'CHT-0129', 'Fashion Dolls - Deluxe Set from our Fashion Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 325.00, 455.00, 20, 55, NULL, 0, 1),
(6, 26, 'Fashion Dolls - Gift Pack', 'fashion-dolls-gift-pack-130', 'CHT-0130', 'Fashion Dolls - Gift Pack from our Fashion Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 350.00, 490.00, 0, 60, NULL, 0, 1),
(6, 27, 'Baby Dolls - Classic Look', 'baby-dolls-classic-look-131', 'CHT-0131', 'Baby Dolls - Classic Look from our Baby Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 375.00, 525.00, 5, 65, NULL, 0, 1),
(6, 27, 'Baby Dolls - Party Wear', 'baby-dolls-party-wear-132', 'CHT-0132', 'Baby Dolls - Party Wear from our Baby Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 400.00, 560.00, 10, 70, NULL, 0, 1),
(6, 27, 'Baby Dolls - Everyday Wear', 'baby-dolls-everyday-wear-133', 'CHT-0133', 'Baby Dolls - Everyday Wear from our Baby Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 425.00, 595.00, 15, 75, NULL, 0, 1),
(6, 27, 'Baby Dolls - Deluxe Set', 'baby-dolls-deluxe-set-134', 'CHT-0134', 'Baby Dolls - Deluxe Set from our Baby Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 450.00, 630.00, 20, 80, NULL, 0, 1),
(6, 27, 'Baby Dolls - Gift Pack', 'baby-dolls-gift-pack-135', 'CHT-0135', 'Baby Dolls - Gift Pack from our Baby Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 475.00, 665.00, 0, 10, NULL, 0, 1),
(6, 28, 'Doll Houses - Classic Look', 'doll-houses-classic-look-136', 'CHT-0136', 'Doll Houses - Classic Look from our Doll Houses range under Dolls & Doll Houses. Safe, durable and fun for kids.', 500.00, 700.00, 5, 15, NULL, 1, 1),
(6, 28, 'Doll Houses - Party Wear', 'doll-houses-party-wear-137', 'CHT-0137', 'Doll Houses - Party Wear from our Doll Houses range under Dolls & Doll Houses. Safe, durable and fun for kids.', 525.00, 735.00, 10, 20, NULL, 0, 1),
(6, 28, 'Doll Houses - Everyday Wear', 'doll-houses-everyday-wear-138', 'CHT-0138', 'Doll Houses - Everyday Wear from our Doll Houses range under Dolls & Doll Houses. Safe, durable and fun for kids.', 550.00, 770.00, 15, 25, NULL, 0, 1),
(6, 28, 'Doll Houses - Deluxe Set', 'doll-houses-deluxe-set-139', 'CHT-0139', 'Doll Houses - Deluxe Set from our Doll Houses range under Dolls & Doll Houses. Safe, durable and fun for kids.', 575.00, 805.00, 20, 30, NULL, 0, 1),
(6, 28, 'Doll Houses - Gift Pack', 'doll-houses-gift-pack-140', 'CHT-0140', 'Doll Houses - Gift Pack from our Doll Houses range under Dolls & Doll Houses. Safe, durable and fun for kids.', 100.00, 140.00, 0, 35, NULL, 0, 1),
(6, 29, 'Doll Accessories - Classic Look', 'doll-accessories-classic-look-141', 'CHT-0141', 'Doll Accessories - Classic Look from our Doll Accessories range under Dolls & Doll Houses. Safe, durable and fun for kids.', 125.00, 175.00, 5, 40, NULL, 0, 1),
(6, 29, 'Doll Accessories - Party Wear', 'doll-accessories-party-wear-142', 'CHT-0142', 'Doll Accessories - Party Wear from our Doll Accessories range under Dolls & Doll Houses. Safe, durable and fun for kids.', 150.00, 210.00, 10, 45, NULL, 0, 1),
(6, 29, 'Doll Accessories - Everyday Wear', 'doll-accessories-everyday-wear-143', 'CHT-0143', 'Doll Accessories - Everyday Wear from our Doll Accessories range under Dolls & Doll Houses. Safe, durable and fun for kids.', 175.00, 245.00, 15, 50, NULL, 0, 1),
(6, 29, 'Doll Accessories - Deluxe Set', 'doll-accessories-deluxe-set-144', 'CHT-0144', 'Doll Accessories - Deluxe Set from our Doll Accessories range under Dolls & Doll Houses. Safe, durable and fun for kids.', 200.00, 280.00, 20, 55, NULL, 0, 1),
(6, 29, 'Doll Accessories - Gift Pack', 'doll-accessories-gift-pack-145', 'CHT-0145', 'Doll Accessories - Gift Pack from our Doll Accessories range under Dolls & Doll Houses. Safe, durable and fun for kids.', 225.00, 315.00, 0, 60, NULL, 0, 1),
(6, 30, 'Princess Dolls - Classic Look', 'princess-dolls-classic-look-146', 'CHT-0146', 'Princess Dolls - Classic Look from our Princess Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 250.00, 350.00, 5, 65, NULL, 0, 1),
(6, 30, 'Princess Dolls - Party Wear', 'princess-dolls-party-wear-147', 'CHT-0147', 'Princess Dolls - Party Wear from our Princess Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 275.00, 385.00, 10, 70, NULL, 0, 1),
(6, 30, 'Princess Dolls - Everyday Wear', 'princess-dolls-everyday-wear-148', 'CHT-0148', 'Princess Dolls - Everyday Wear from our Princess Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 300.00, 420.00, 15, 75, NULL, 0, 1),
(6, 30, 'Princess Dolls - Deluxe Set', 'princess-dolls-deluxe-set-149', 'CHT-0149', 'Princess Dolls - Deluxe Set from our Princess Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 325.00, 455.00, 20, 80, NULL, 0, 1),
(6, 30, 'Princess Dolls - Gift Pack', 'princess-dolls-gift-pack-150', 'CHT-0150', 'Princess Dolls - Gift Pack from our Princess Dolls range under Dolls & Doll Houses. Safe, durable and fun for kids.', 350.00, 490.00, 0, 10, NULL, 0, 1),
(7, 31, 'Bicycles & Tricycles - Junior Size', 'bicycles-and-tricycles-junior-size-151', 'CHT-0151', 'Bicycles & Tricycles - Junior Size from our Bicycles & Tricycles range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 375.00, 525.00, 5, 15, NULL, 0, 1),
(7, 31, 'Bicycles & Tricycles - Standard Size', 'bicycles-and-tricycles-standard-size-152', 'CHT-0152', 'Bicycles & Tricycles - Standard Size from our Bicycles & Tricycles range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 400.00, 560.00, 10, 20, NULL, 0, 1),
(7, 31, 'Bicycles & Tricycles - Compact Size', 'bicycles-and-tricycles-compact-size-153', 'CHT-0153', 'Bicycles & Tricycles - Compact Size from our Bicycles & Tricycles range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 425.00, 595.00, 15, 25, NULL, 1, 1),
(7, 31, 'Bicycles & Tricycles - Family Pack', 'bicycles-and-tricycles-family-pack-154', 'CHT-0154', 'Bicycles & Tricycles - Family Pack from our Bicycles & Tricycles range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 450.00, 630.00, 20, 30, NULL, 0, 1),
(7, 31, 'Bicycles & Tricycles - Pro Model', 'bicycles-and-tricycles-pro-model-155', 'CHT-0155', 'Bicycles & Tricycles - Pro Model from our Bicycles & Tricycles range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 475.00, 665.00, 0, 35, NULL, 0, 1),
(7, 32, 'Balls & Sports Sets - Junior Size', 'balls-and-sports-sets-junior-size-156', 'CHT-0156', 'Balls & Sports Sets - Junior Size from our Balls & Sports Sets range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 500.00, 700.00, 5, 40, NULL, 0, 1),
(7, 32, 'Balls & Sports Sets - Standard Size', 'balls-and-sports-sets-standard-size-157', 'CHT-0157', 'Balls & Sports Sets - Standard Size from our Balls & Sports Sets range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 525.00, 735.00, 10, 45, NULL, 0, 1),
(7, 32, 'Balls & Sports Sets - Compact Size', 'balls-and-sports-sets-compact-size-158', 'CHT-0158', 'Balls & Sports Sets - Compact Size from our Balls & Sports Sets range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 550.00, 770.00, 15, 50, NULL, 0, 1),
(7, 32, 'Balls & Sports Sets - Family Pack', 'balls-and-sports-sets-family-pack-159', 'CHT-0159', 'Balls & Sports Sets - Family Pack from our Balls & Sports Sets range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 575.00, 805.00, 20, 55, NULL, 0, 1),
(7, 32, 'Balls & Sports Sets - Pro Model', 'balls-and-sports-sets-pro-model-160', 'CHT-0160', 'Balls & Sports Sets - Pro Model from our Balls & Sports Sets range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 100.00, 140.00, 0, 60, NULL, 0, 1),
(7, 33, 'Water Toys - Junior Size', 'water-toys-junior-size-161', 'CHT-0161', 'Water Toys - Junior Size from our Water Toys range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 125.00, 175.00, 5, 65, NULL, 0, 1),
(7, 33, 'Water Toys - Standard Size', 'water-toys-standard-size-162', 'CHT-0162', 'Water Toys - Standard Size from our Water Toys range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 150.00, 210.00, 10, 70, NULL, 0, 1),
(7, 33, 'Water Toys - Compact Size', 'water-toys-compact-size-163', 'CHT-0163', 'Water Toys - Compact Size from our Water Toys range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 175.00, 245.00, 15, 75, NULL, 0, 1),
(7, 33, 'Water Toys - Family Pack', 'water-toys-family-pack-164', 'CHT-0164', 'Water Toys - Family Pack from our Water Toys range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 200.00, 280.00, 20, 80, NULL, 0, 1),
(7, 33, 'Water Toys - Pro Model', 'water-toys-pro-model-165', 'CHT-0165', 'Water Toys - Pro Model from our Water Toys range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 225.00, 315.00, 0, 10, NULL, 0, 1),
(7, 34, 'Swings & Slides - Junior Size', 'swings-and-slides-junior-size-166', 'CHT-0166', 'Swings & Slides - Junior Size from our Swings & Slides range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 250.00, 350.00, 5, 15, NULL, 0, 1),
(7, 34, 'Swings & Slides - Standard Size', 'swings-and-slides-standard-size-167', 'CHT-0167', 'Swings & Slides - Standard Size from our Swings & Slides range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 275.00, 385.00, 10, 20, NULL, 0, 1),
(7, 34, 'Swings & Slides - Compact Size', 'swings-and-slides-compact-size-168', 'CHT-0168', 'Swings & Slides - Compact Size from our Swings & Slides range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 300.00, 420.00, 15, 25, NULL, 0, 1),
(7, 34, 'Swings & Slides - Family Pack', 'swings-and-slides-family-pack-169', 'CHT-0169', 'Swings & Slides - Family Pack from our Swings & Slides range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 325.00, 455.00, 20, 30, NULL, 0, 1),
(7, 34, 'Swings & Slides - Pro Model', 'swings-and-slides-pro-model-170', 'CHT-0170', 'Swings & Slides - Pro Model from our Swings & Slides range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 350.00, 490.00, 0, 35, NULL, 1, 1),
(7, 35, 'Skating & Scooters - Junior Size', 'skating-and-scooters-junior-size-171', 'CHT-0171', 'Skating & Scooters - Junior Size from our Skating & Scooters range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 375.00, 525.00, 5, 40, NULL, 0, 1),
(7, 35, 'Skating & Scooters - Standard Size', 'skating-and-scooters-standard-size-172', 'CHT-0172', 'Skating & Scooters - Standard Size from our Skating & Scooters range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 400.00, 560.00, 10, 45, NULL, 0, 1),
(7, 35, 'Skating & Scooters - Compact Size', 'skating-and-scooters-compact-size-173', 'CHT-0173', 'Skating & Scooters - Compact Size from our Skating & Scooters range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 425.00, 595.00, 15, 50, NULL, 0, 1),
(7, 35, 'Skating & Scooters - Family Pack', 'skating-and-scooters-family-pack-174', 'CHT-0174', 'Skating & Scooters - Family Pack from our Skating & Scooters range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 450.00, 630.00, 20, 55, NULL, 0, 1),
(7, 35, 'Skating & Scooters - Pro Model', 'skating-and-scooters-pro-model-175', 'CHT-0175', 'Skating & Scooters - Pro Model from our Skating & Scooters range under Outdoor & Sports Toys. Safe, durable and fun for kids.', 475.00, 665.00, 0, 60, NULL, 0, 1),
(8, 36, 'Jigsaw Puzzles - 24 Piece', 'jigsaw-puzzles-24-piece-176', 'CHT-0176', 'Jigsaw Puzzles - 24 Piece from our Jigsaw Puzzles range under Puzzles & Board Games. Safe, durable and fun for kids.', 500.00, 700.00, 5, 65, NULL, 0, 1),
(8, 36, 'Jigsaw Puzzles - 48 Piece', 'jigsaw-puzzles-48-piece-177', 'CHT-0177', 'Jigsaw Puzzles - 48 Piece from our Jigsaw Puzzles range under Puzzles & Board Games. Safe, durable and fun for kids.', 525.00, 735.00, 10, 70, NULL, 0, 1),
(8, 36, 'Jigsaw Puzzles - 100 Piece', 'jigsaw-puzzles-100-piece-178', 'CHT-0178', 'Jigsaw Puzzles - 100 Piece from our Jigsaw Puzzles range under Puzzles & Board Games. Safe, durable and fun for kids.', 550.00, 770.00, 15, 75, NULL, 0, 1),
(8, 36, 'Jigsaw Puzzles - 2-4 Player', 'jigsaw-puzzles-2-4-player-179', 'CHT-0179', 'Jigsaw Puzzles - 2-4 Player from our Jigsaw Puzzles range under Puzzles & Board Games. Safe, durable and fun for kids.', 575.00, 805.00, 20, 80, NULL, 0, 1),
(8, 36, 'Jigsaw Puzzles - Family Edition', 'jigsaw-puzzles-family-edition-180', 'CHT-0180', 'Jigsaw Puzzles - Family Edition from our Jigsaw Puzzles range under Puzzles & Board Games. Safe, durable and fun for kids.', 100.00, 140.00, 0, 10, NULL, 0, 1),
(8, 37, 'Wooden Puzzles - 24 Piece', 'wooden-puzzles-24-piece-181', 'CHT-0181', 'Wooden Puzzles - 24 Piece from our Wooden Puzzles range under Puzzles & Board Games. Safe, durable and fun for kids.', 125.00, 175.00, 5, 15, NULL, 0, 1),
(8, 37, 'Wooden Puzzles - 48 Piece', 'wooden-puzzles-48-piece-182', 'CHT-0182', 'Wooden Puzzles - 48 Piece from our Wooden Puzzles range under Puzzles & Board Games. Safe, durable and fun for kids.', 150.00, 210.00, 10, 20, NULL, 0, 1),
(8, 37, 'Wooden Puzzles - 100 Piece', 'wooden-puzzles-100-piece-183', 'CHT-0183', 'Wooden Puzzles - 100 Piece from our Wooden Puzzles range under Puzzles & Board Games. Safe, durable and fun for kids.', 175.00, 245.00, 15, 25, NULL, 0, 1),
(8, 37, 'Wooden Puzzles - 2-4 Player', 'wooden-puzzles-2-4-player-184', 'CHT-0184', 'Wooden Puzzles - 2-4 Player from our Wooden Puzzles range under Puzzles & Board Games. Safe, durable and fun for kids.', 200.00, 280.00, 20, 30, NULL, 0, 1),
(8, 37, 'Wooden Puzzles - Family Edition', 'wooden-puzzles-family-edition-185', 'CHT-0185', 'Wooden Puzzles - Family Edition from our Wooden Puzzles range under Puzzles & Board Games. Safe, durable and fun for kids.', 225.00, 315.00, 0, 35, NULL, 0, 1),
(8, 38, 'Family Board Games - 24 Piece', 'family-board-games-24-piece-186', 'CHT-0186', 'Family Board Games - 24 Piece from our Family Board Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 250.00, 350.00, 5, 40, NULL, 0, 1),
(8, 38, 'Family Board Games - 48 Piece', 'family-board-games-48-piece-187', 'CHT-0187', 'Family Board Games - 48 Piece from our Family Board Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 275.00, 385.00, 10, 45, NULL, 1, 1),
(8, 38, 'Family Board Games - 100 Piece', 'family-board-games-100-piece-188', 'CHT-0188', 'Family Board Games - 100 Piece from our Family Board Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 300.00, 420.00, 15, 50, NULL, 0, 1),
(8, 38, 'Family Board Games - 2-4 Player', 'family-board-games-2-4-player-189', 'CHT-0189', 'Family Board Games - 2-4 Player from our Family Board Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 325.00, 455.00, 20, 55, NULL, 0, 1),
(8, 38, 'Family Board Games - Family Edition', 'family-board-games-family-edition-190', 'CHT-0190', 'Family Board Games - Family Edition from our Family Board Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 350.00, 490.00, 0, 60, NULL, 0, 1),
(8, 39, 'Card Games - 24 Piece', 'card-games-24-piece-191', 'CHT-0191', 'Card Games - 24 Piece from our Card Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 375.00, 525.00, 5, 65, NULL, 0, 1),
(8, 39, 'Card Games - 48 Piece', 'card-games-48-piece-192', 'CHT-0192', 'Card Games - 48 Piece from our Card Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 400.00, 560.00, 10, 70, NULL, 0, 1),
(8, 39, 'Card Games - 100 Piece', 'card-games-100-piece-193', 'CHT-0193', 'Card Games - 100 Piece from our Card Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 425.00, 595.00, 15, 75, NULL, 0, 1),
(8, 39, 'Card Games - 2-4 Player', 'card-games-2-4-player-194', 'CHT-0194', 'Card Games - 2-4 Player from our Card Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 450.00, 630.00, 20, 80, NULL, 0, 1),
(8, 39, 'Card Games - Family Edition', 'card-games-family-edition-195', 'CHT-0195', 'Card Games - Family Edition from our Card Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 475.00, 665.00, 0, 10, NULL, 0, 1),
(8, 40, 'Strategy Games - 24 Piece', 'strategy-games-24-piece-196', 'CHT-0196', 'Strategy Games - 24 Piece from our Strategy Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 500.00, 700.00, 5, 15, NULL, 0, 1),
(8, 40, 'Strategy Games - 48 Piece', 'strategy-games-48-piece-197', 'CHT-0197', 'Strategy Games - 48 Piece from our Strategy Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 525.00, 735.00, 10, 20, NULL, 0, 1),
(8, 40, 'Strategy Games - 100 Piece', 'strategy-games-100-piece-198', 'CHT-0198', 'Strategy Games - 100 Piece from our Strategy Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 550.00, 770.00, 15, 25, NULL, 0, 1),
(8, 40, 'Strategy Games - 2-4 Player', 'strategy-games-2-4-player-199', 'CHT-0199', 'Strategy Games - 2-4 Player from our Strategy Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 575.00, 805.00, 20, 30, NULL, 0, 1),
(8, 40, 'Strategy Games - Family Edition', 'strategy-games-family-edition-200', 'CHT-0200', 'Strategy Games - Family Edition from our Strategy Games range under Puzzles & Board Games. Safe, durable and fun for kids.', 100.00, 140.00, 0, 35, NULL, 0, 1),
(9, 41, 'Toy Instruments - Junior Model', 'toy-instruments-junior-model-201', 'CHT-0201', 'Toy Instruments - Junior Model from our Toy Instruments range under Musical Toys. Safe, durable and fun for kids.', 125.00, 175.00, 5, 40, NULL, 0, 1),
(9, 41, 'Toy Instruments - Standard Model', 'toy-instruments-standard-model-202', 'CHT-0202', 'Toy Instruments - Standard Model from our Toy Instruments range under Musical Toys. Safe, durable and fun for kids.', 150.00, 210.00, 10, 45, NULL, 0, 1),
(9, 41, 'Toy Instruments - Mini Set', 'toy-instruments-mini-set-203', 'CHT-0203', 'Toy Instruments - Mini Set from our Toy Instruments range under Musical Toys. Safe, durable and fun for kids.', 175.00, 245.00, 15, 50, NULL, 0, 1),
(9, 41, 'Toy Instruments - Deluxe Model', 'toy-instruments-deluxe-model-204', 'CHT-0204', 'Toy Instruments - Deluxe Model from our Toy Instruments range under Musical Toys. Safe, durable and fun for kids.', 200.00, 280.00, 20, 55, NULL, 1, 1),
(9, 41, 'Toy Instruments - Starter Set', 'toy-instruments-starter-set-205', 'CHT-0205', 'Toy Instruments - Starter Set from our Toy Instruments range under Musical Toys. Safe, durable and fun for kids.', 225.00, 315.00, 0, 60, NULL, 0, 1),
(9, 42, 'Musical Learning Toys - Junior Model', 'musical-learning-toys-junior-model-206', 'CHT-0206', 'Musical Learning Toys - Junior Model from our Musical Learning Toys range under Musical Toys. Safe, durable and fun for kids.', 250.00, 350.00, 5, 65, NULL, 0, 1),
(9, 42, 'Musical Learning Toys - Standard Model', 'musical-learning-toys-standard-model-207', 'CHT-0207', 'Musical Learning Toys - Standard Model from our Musical Learning Toys range under Musical Toys. Safe, durable and fun for kids.', 275.00, 385.00, 10, 70, NULL, 0, 1),
(9, 42, 'Musical Learning Toys - Mini Set', 'musical-learning-toys-mini-set-208', 'CHT-0208', 'Musical Learning Toys - Mini Set from our Musical Learning Toys range under Musical Toys. Safe, durable and fun for kids.', 300.00, 420.00, 15, 75, NULL, 0, 1),
(9, 42, 'Musical Learning Toys - Deluxe Model', 'musical-learning-toys-deluxe-model-209', 'CHT-0209', 'Musical Learning Toys - Deluxe Model from our Musical Learning Toys range under Musical Toys. Safe, durable and fun for kids.', 325.00, 455.00, 20, 80, NULL, 0, 1),
(9, 42, 'Musical Learning Toys - Starter Set', 'musical-learning-toys-starter-set-210', 'CHT-0210', 'Musical Learning Toys - Starter Set from our Musical Learning Toys range under Musical Toys. Safe, durable and fun for kids.', 350.00, 490.00, 0, 10, NULL, 0, 1),
(9, 43, 'Karaoke & Sing-Along - Junior Model', 'karaoke-and-sing-along-junior-model-211', 'CHT-0211', 'Karaoke & Sing-Along - Junior Model from our Karaoke & Sing-Along range under Musical Toys. Safe, durable and fun for kids.', 375.00, 525.00, 5, 15, NULL, 0, 1),
(9, 43, 'Karaoke & Sing-Along - Standard Model', 'karaoke-and-sing-along-standard-model-212', 'CHT-0212', 'Karaoke & Sing-Along - Standard Model from our Karaoke & Sing-Along range under Musical Toys. Safe, durable and fun for kids.', 400.00, 560.00, 10, 20, NULL, 0, 1),
(9, 43, 'Karaoke & Sing-Along - Mini Set', 'karaoke-and-sing-along-mini-set-213', 'CHT-0213', 'Karaoke & Sing-Along - Mini Set from our Karaoke & Sing-Along range under Musical Toys. Safe, durable and fun for kids.', 425.00, 595.00, 15, 25, NULL, 0, 1),
(9, 43, 'Karaoke & Sing-Along - Deluxe Model', 'karaoke-and-sing-along-deluxe-model-214', 'CHT-0214', 'Karaoke & Sing-Along - Deluxe Model from our Karaoke & Sing-Along range under Musical Toys. Safe, durable and fun for kids.', 450.00, 630.00, 20, 30, NULL, 0, 1),
(9, 43, 'Karaoke & Sing-Along - Starter Set', 'karaoke-and-sing-along-starter-set-215', 'CHT-0215', 'Karaoke & Sing-Along - Starter Set from our Karaoke & Sing-Along range under Musical Toys. Safe, durable and fun for kids.', 475.00, 665.00, 0, 35, NULL, 0, 1),
(9, 44, 'Drum Sets - Junior Model', 'drum-sets-junior-model-216', 'CHT-0216', 'Drum Sets - Junior Model from our Drum Sets range under Musical Toys. Safe, durable and fun for kids.', 500.00, 700.00, 5, 40, NULL, 0, 1),
(9, 44, 'Drum Sets - Standard Model', 'drum-sets-standard-model-217', 'CHT-0217', 'Drum Sets - Standard Model from our Drum Sets range under Musical Toys. Safe, durable and fun for kids.', 525.00, 735.00, 10, 45, NULL, 0, 1),
(9, 44, 'Drum Sets - Mini Set', 'drum-sets-mini-set-218', 'CHT-0218', 'Drum Sets - Mini Set from our Drum Sets range under Musical Toys. Safe, durable and fun for kids.', 550.00, 770.00, 15, 50, NULL, 0, 1),
(9, 44, 'Drum Sets - Deluxe Model', 'drum-sets-deluxe-model-219', 'CHT-0219', 'Drum Sets - Deluxe Model from our Drum Sets range under Musical Toys. Safe, durable and fun for kids.', 575.00, 805.00, 20, 55, NULL, 0, 1),
(9, 44, 'Drum Sets - Starter Set', 'drum-sets-starter-set-220', 'CHT-0220', 'Drum Sets - Starter Set from our Drum Sets range under Musical Toys. Safe, durable and fun for kids.', 100.00, 140.00, 0, 60, NULL, 0, 1),
(9, 45, 'Piano & Keyboard Toys - Junior Model', 'piano-and-keyboard-toys-junior-model-221', 'CHT-0221', 'Piano & Keyboard Toys - Junior Model from our Piano & Keyboard Toys range under Musical Toys. Safe, durable and fun for kids.', 125.00, 175.00, 5, 65, NULL, 1, 1),
(9, 45, 'Piano & Keyboard Toys - Standard Model', 'piano-and-keyboard-toys-standard-model-222', 'CHT-0222', 'Piano & Keyboard Toys - Standard Model from our Piano & Keyboard Toys range under Musical Toys. Safe, durable and fun for kids.', 150.00, 210.00, 10, 70, NULL, 0, 1),
(9, 45, 'Piano & Keyboard Toys - Mini Set', 'piano-and-keyboard-toys-mini-set-223', 'CHT-0223', 'Piano & Keyboard Toys - Mini Set from our Piano & Keyboard Toys range under Musical Toys. Safe, durable and fun for kids.', 175.00, 245.00, 15, 75, NULL, 0, 1),
(9, 45, 'Piano & Keyboard Toys - Deluxe Model', 'piano-and-keyboard-toys-deluxe-model-224', 'CHT-0224', 'Piano & Keyboard Toys - Deluxe Model from our Piano & Keyboard Toys range under Musical Toys. Safe, durable and fun for kids.', 200.00, 280.00, 20, 80, NULL, 0, 1),
(9, 45, 'Piano & Keyboard Toys - Starter Set', 'piano-and-keyboard-toys-starter-set-225', 'CHT-0225', 'Piano & Keyboard Toys - Starter Set from our Piano & Keyboard Toys range under Musical Toys. Safe, durable and fun for kids.', 225.00, 315.00, 0, 10, NULL, 0, 1),
(10, 46, 'Rattles & Teethers - Soft Pack', 'rattles-and-teethers-soft-pack-226', 'CHT-0226', 'Rattles & Teethers - Soft Pack from our Rattles & Teethers range under Baby & Infant Toys. Safe, durable and fun for kids.', 250.00, 350.00, 5, 15, NULL, 0, 1),
(10, 46, 'Rattles & Teethers - Colorful Set', 'rattles-and-teethers-colorful-set-227', 'CHT-0227', 'Rattles & Teethers - Colorful Set from our Rattles & Teethers range under Baby & Infant Toys. Safe, durable and fun for kids.', 275.00, 385.00, 10, 20, NULL, 0, 1),
(10, 46, 'Rattles & Teethers - Sensory Pack', 'rattles-and-teethers-sensory-pack-228', 'CHT-0228', 'Rattles & Teethers - Sensory Pack from our Rattles & Teethers range under Baby & Infant Toys. Safe, durable and fun for kids.', 300.00, 420.00, 15, 25, NULL, 0, 1),
(10, 46, 'Rattles & Teethers - Newborn Set', 'rattles-and-teethers-newborn-set-229', 'CHT-0229', 'Rattles & Teethers - Newborn Set from our Rattles & Teethers range under Baby & Infant Toys. Safe, durable and fun for kids.', 325.00, 455.00, 20, 30, NULL, 0, 1),
(10, 46, 'Rattles & Teethers - Toddler Pack', 'rattles-and-teethers-toddler-pack-230', 'CHT-0230', 'Rattles & Teethers - Toddler Pack from our Rattles & Teethers range under Baby & Infant Toys. Safe, durable and fun for kids.', 350.00, 490.00, 0, 35, NULL, 0, 1),
(10, 47, 'Baby Gyms & Mobiles - Soft Pack', 'baby-gyms-and-mobiles-soft-pack-231', 'CHT-0231', 'Baby Gyms & Mobiles - Soft Pack from our Baby Gyms & Mobiles range under Baby & Infant Toys. Safe, durable and fun for kids.', 375.00, 525.00, 5, 40, NULL, 0, 1),
(10, 47, 'Baby Gyms & Mobiles - Colorful Set', 'baby-gyms-and-mobiles-colorful-set-232', 'CHT-0232', 'Baby Gyms & Mobiles - Colorful Set from our Baby Gyms & Mobiles range under Baby & Infant Toys. Safe, durable and fun for kids.', 400.00, 560.00, 10, 45, NULL, 0, 1),
(10, 47, 'Baby Gyms & Mobiles - Sensory Pack', 'baby-gyms-and-mobiles-sensory-pack-233', 'CHT-0233', 'Baby Gyms & Mobiles - Sensory Pack from our Baby Gyms & Mobiles range under Baby & Infant Toys. Safe, durable and fun for kids.', 425.00, 595.00, 15, 50, NULL, 0, 1),
(10, 47, 'Baby Gyms & Mobiles - Newborn Set', 'baby-gyms-and-mobiles-newborn-set-234', 'CHT-0234', 'Baby Gyms & Mobiles - Newborn Set from our Baby Gyms & Mobiles range under Baby & Infant Toys. Safe, durable and fun for kids.', 450.00, 630.00, 20, 55, NULL, 0, 1),
(10, 47, 'Baby Gyms & Mobiles - Toddler Pack', 'baby-gyms-and-mobiles-toddler-pack-235', 'CHT-0235', 'Baby Gyms & Mobiles - Toddler Pack from our Baby Gyms & Mobiles range under Baby & Infant Toys. Safe, durable and fun for kids.', 475.00, 665.00, 0, 60, NULL, 0, 1),
(10, 48, 'Stacking & Sorting Toys - Soft Pack', 'stacking-and-sorting-toys-soft-pack-236', 'CHT-0236', 'Stacking & Sorting Toys - Soft Pack from our Stacking & Sorting Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 500.00, 700.00, 5, 65, NULL, 0, 1),
(10, 48, 'Stacking & Sorting Toys - Colorful Set', 'stacking-and-sorting-toys-colorful-set-237', 'CHT-0237', 'Stacking & Sorting Toys - Colorful Set from our Stacking & Sorting Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 525.00, 735.00, 10, 70, NULL, 0, 1),
(10, 48, 'Stacking & Sorting Toys - Sensory Pack', 'stacking-and-sorting-toys-sensory-pack-238', 'CHT-0238', 'Stacking & Sorting Toys - Sensory Pack from our Stacking & Sorting Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 550.00, 770.00, 15, 75, NULL, 1, 1),
(10, 48, 'Stacking & Sorting Toys - Newborn Set', 'stacking-and-sorting-toys-newborn-set-239', 'CHT-0239', 'Stacking & Sorting Toys - Newborn Set from our Stacking & Sorting Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 575.00, 805.00, 20, 80, NULL, 0, 1),
(10, 48, 'Stacking & Sorting Toys - Toddler Pack', 'stacking-and-sorting-toys-toddler-pack-240', 'CHT-0240', 'Stacking & Sorting Toys - Toddler Pack from our Stacking & Sorting Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 100.00, 140.00, 0, 10, NULL, 0, 1),
(10, 49, 'Bath Toys - Soft Pack', 'bath-toys-soft-pack-241', 'CHT-0241', 'Bath Toys - Soft Pack from our Bath Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 125.00, 175.00, 5, 15, NULL, 0, 1),
(10, 49, 'Bath Toys - Colorful Set', 'bath-toys-colorful-set-242', 'CHT-0242', 'Bath Toys - Colorful Set from our Bath Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 150.00, 210.00, 10, 20, NULL, 0, 1),
(10, 49, 'Bath Toys - Sensory Pack', 'bath-toys-sensory-pack-243', 'CHT-0243', 'Bath Toys - Sensory Pack from our Bath Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 175.00, 245.00, 15, 25, NULL, 0, 1),
(10, 49, 'Bath Toys - Newborn Set', 'bath-toys-newborn-set-244', 'CHT-0244', 'Bath Toys - Newborn Set from our Bath Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 200.00, 280.00, 20, 30, NULL, 0, 1),
(10, 49, 'Bath Toys - Toddler Pack', 'bath-toys-toddler-pack-245', 'CHT-0245', 'Bath Toys - Toddler Pack from our Bath Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 225.00, 315.00, 0, 35, NULL, 0, 1),
(10, 50, 'Push & Pull Toys - Soft Pack', 'push-and-pull-toys-soft-pack-246', 'CHT-0246', 'Push & Pull Toys - Soft Pack from our Push & Pull Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 250.00, 350.00, 5, 40, NULL, 0, 1),
(10, 50, 'Push & Pull Toys - Colorful Set', 'push-and-pull-toys-colorful-set-247', 'CHT-0247', 'Push & Pull Toys - Colorful Set from our Push & Pull Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 275.00, 385.00, 10, 45, NULL, 0, 1),
(10, 50, 'Push & Pull Toys - Sensory Pack', 'push-and-pull-toys-sensory-pack-248', 'CHT-0248', 'Push & Pull Toys - Sensory Pack from our Push & Pull Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 300.00, 420.00, 15, 50, NULL, 0, 1),
(10, 50, 'Push & Pull Toys - Newborn Set', 'push-and-pull-toys-newborn-set-249', 'CHT-0249', 'Push & Pull Toys - Newborn Set from our Push & Pull Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 325.00, 455.00, 20, 55, NULL, 0, 1),
(10, 50, 'Push & Pull Toys - Toddler Pack', 'push-and-pull-toys-toddler-pack-250', 'CHT-0250', 'Push & Pull Toys - Toddler Pack from our Push & Pull Toys range under Baby & Infant Toys. Safe, durable and fun for kids.', 350.00, 490.00, 0, 60, NULL, 0, 1);

-- Total categories: 10
-- Total subcategories: 50
-- Total products: 250
